-- ============================================================
-- 冀遗筑梦 · Supabase 迁移脚本
-- 修正历史遗留表结构 + 补齐 products / orders 两张表
-- + 索引 + 统计函数 + 种子商品
--
-- 执行方式：Supabase Dashboard → 左侧 SQL Editor → New query
--           → 全文粘贴 → Run（或 Ctrl+Enter）
--
-- 本脚本幂等，可反复执行。
-- 前置：supabase-init.sql 已执行（users/carts/favorites/user_logs 已存在）
-- ============================================================


-- ---------- 0. 修正历史遗留表结构 ----------
-- 背景：线上 carts / favorites 是更早的某个脚本建的，用的是 user_id 外键；
--       而应用层（backend/db.js）与仓库自带的 supabase-init.sql 全程用 username。
--       两边对不上的后果：往购物车写入直接报
--         PGRST204 Could not find the 'username' column of 'carts' in the schema cache
--       表现为「前端提示加购成功，但购物车永远是空的」——一个静默的功能损坏。
--
-- 下面只在「该表仍是 user_id 版本、且一行数据都没有」时才重建；
-- 一旦发现表里有数据就 RAISE EXCEPTION 中止，绝不静默丢数据。
DO $$
DECLARE
    n BIGINT;
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns
                WHERE table_schema = 'public' AND table_name = 'carts'
                  AND column_name = 'user_id')
       AND NOT EXISTS (SELECT 1 FROM information_schema.columns
                WHERE table_schema = 'public' AND table_name = 'carts'
                  AND column_name = 'username')
    THEN
        SELECT COUNT(*) INTO n FROM carts;
        IF n > 0 THEN
            RAISE EXCEPTION 'carts 表有 % 行数据，需先人工迁移再用本脚本重建', n;
        END IF;
        DROP TABLE carts;
        RAISE NOTICE 'carts 已重建为 username 版本';
    END IF;

    IF EXISTS (SELECT 1 FROM information_schema.columns
                WHERE table_schema = 'public' AND table_name = 'favorites'
                  AND column_name = 'user_id')
       AND NOT EXISTS (SELECT 1 FROM information_schema.columns
                WHERE table_schema = 'public' AND table_name = 'favorites'
                  AND column_name = 'username')
    THEN
        SELECT COUNT(*) INTO n FROM favorites;
        IF n > 0 THEN
            RAISE EXCEPTION 'favorites 表有 % 行数据，需先人工迁移再用本脚本重建', n;
        END IF;
        DROP TABLE favorites;
        RAISE NOTICE 'favorites 已重建为 username 版本';
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS carts (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   TEXT NOT NULL,
    product    JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS favorites (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   TEXT NOT NULL,
    product    JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_carts_username     ON carts(username);
CREATE INDEX IF NOT EXISTS idx_favorites_username ON favorites(username);


-- ---------- 1. 商品表 ----------
-- active 必须是 INTEGER 而不是 BOOLEAN：
--   backend/index.js 里有 `p.active === 1` 的严格比较，
--   改成 BOOLEAN 会让 /api/products/:id 全部返回 404。
CREATE TABLE IF NOT EXISTS products (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT NOT NULL,
    price      DOUBLE PRECISION NOT NULL DEFAULT 0,
    img        TEXT NOT NULL DEFAULT '',
    category   TEXT NOT NULL DEFAULT '非遗手作',
    active     INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT products_active_check CHECK (active IN (0, 1))
);

-- price 用 DOUBLE PRECISION 而非 NUMERIC：
--   PostgREST 会把 NUMERIC 序列化成 JSON 字符串，
--   导致后台 admin.html 的 kpi.revenue.toLocaleString() 静默丢掉千分位。
--   DOUBLE PRECISION 与旧 SQLite 的 REAL 语义逐字对应。


-- ---------- 2. 订单表 ----------
CREATE TABLE IF NOT EXISTS orders (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   TEXT NOT NULL,
    total      DOUBLE PRECISION NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ---------- 3. 索引 ----------
CREATE INDEX IF NOT EXISTS idx_products_active     ON products(active);
CREATE INDEX IF NOT EXISTS idx_products_created_at ON products(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_username     ON orders(username);
CREATE INDEX IF NOT EXISTS idx_orders_created_at   ON orders(created_at DESC);


-- ---------- 4. 统计函数 ----------
-- 为什么必须用函数而不能用 .select('total.sum()')：
--   hosted Supabase 把 PostgREST 的 db-aggregates-enabled 锁死为 false，
--   客户端聚合会返回 PGRST123: Use of aggregate functions is not allowed。
-- 为什么不用 .or('action.like.%支付%')：
--   supabase-js 的 .like() 不编码 pattern，'%支' 是非法百分号转义，
--   会被 Supabase 边缘节点拒绝（Cloudflare error 1101 / HTTP 556）。
--
-- 语义与旧 SQLite 版完全一致（见旧 db.js 的 getLatestStats）。
CREATE OR REPLACE FUNCTION get_latest_stats()
RETURNS TABLE(total_orders BIGINT, total_revenue DOUBLE PRECISION)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT
        (SELECT COUNT(*) FROM user_logs
          WHERE action LIKE '%支付%' OR action LIKE '%结算%') AS total_orders,
        (SELECT COALESCE(SUM(total), 0) FROM orders)           AS total_revenue;
$$;


-- ---------- 5. 权限 ----------
-- 后端只使用 service_role 密钥（密钥仅存在于 Render 服务端，绝不下发到浏览器），
-- 因此这里刻意不向 anon / authenticated 授权。
GRANT EXECUTE ON FUNCTION get_latest_stats() TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON products  TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON orders    TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON carts     TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON favorites TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;


-- ---------- 6. 种子商品 ----------
-- 仅当 products 为空时插入，等价于旧 db.js 的 seedData()。
-- 即使这里没插入，服务启动时 db.js 也会自动补上（双保险）。
INSERT INTO products (name, price, img, category)
SELECT * FROM (VALUES
    ('冀筑华塔微藏盒', 198, '/images/001.jpg', '数字藏品'),
    ('赵州桥榫卯奇盒',  88, '/images/002.jpg', '文创周边'),
    ('承德御苑宸景盒', 328, '/images/003.jpg', '数字画作'),
    ('山海关雄关守盒', 999, '/images/004.jpg', '典藏精品'),
    ('隆兴寺禅筑臻盒',  58, '/images/005.jpg', '非遗手作'),
    ('开元寺塔料敌盒', 168, '/images/006.jpg', '非遗手作'),
    ('清西陵宫阙雅盒', 258, '/images/101.jpg', '数字藏品'),
    ('娲皇宫悬楼秘盒', 128, '/images/102.jpg', '文创周边'),
    ('古莲花池苑趣盒', 298, '/images/103.jpg', '数字画作'),
    ('紫荆关燕塞筑盒', 888, '/images/104.jpg', '典藏精品'),
    ('广府古城围合盒',  78, '/images/105.jpg', '非遗手作'),
    ('外八庙梵筑珍盒', 188, '/images/106.jpg', '非遗手作')
) AS v(name, price, img, category)
WHERE NOT EXISTS (SELECT 1 FROM products);


-- ---------- 7. 自检 ----------
-- 期望：product_count = 12
SELECT COUNT(*) AS product_count FROM products;

-- 期望：返回一行，total_orders = 0，total_revenue = 0
SELECT * FROM get_latest_stats();

-- 期望：两行都显示 username，也就是 carts / favorites 已经是应用层要的结构
SELECT table_name, column_name, data_type
  FROM information_schema.columns
 WHERE table_schema = 'public'
   AND table_name IN ('carts', 'favorites')
   AND column_name IN ('username', 'user_id')
 ORDER BY table_name, column_name;
