-- ============================================================
-- 冀遗筑梦 · 迁移 v2：订单明细 + 订单状态 + 购物车数量
--
-- 执行方式：Supabase Dashboard → 左侧 SQL Editor → New query
--           → 全文粘贴 → Run（或 Ctrl+Enter）
--
-- 前置：supabase-migration.sql 已执行（products / orders / carts / favorites 已存在）
-- 本脚本幂等，可反复执行。
--
-- ⚠️ 必须在部署新版后端代码之前执行。
--    新版 index.js 的结算接口会往 order_items 写数据，
--    表不存在的话下单会直接 500。
-- ============================================================


-- ---------- 1. orders 补状态与收货信息 ----------
-- 为什么都带 DEFAULT：orders 表里已经有真实订单行，
-- 加 NOT NULL 列时不给默认值会直接报错、整条 ALTER 失败。
-- 现有行会得到 '待发货' / 空串，语义上正确（它们确实是历史成交单）。

ALTER TABLE orders ADD COLUMN IF NOT EXISTS status   TEXT NOT NULL DEFAULT '待发货';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS address  TEXT NOT NULL DEFAULT '';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS phone    TEXT NOT NULL DEFAULT '';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS order_no TEXT;

-- 订单号：形如 JY20260927-8F3A2C，给用户看的，不暴露自增 id
CREATE UNIQUE INDEX IF NOT EXISTS idx_orders_order_no ON orders(order_no)
    WHERE order_no IS NOT NULL;

-- 「我的订单」按用户名查、按时间倒序，走这个索引
CREATE INDEX IF NOT EXISTS idx_orders_user_time ON orders(username, created_at DESC);


-- ---------- 2. order_items：订单明细 ----------
-- 这是本次迁移的核心。在此之前 orders 只有 (username, total, created_at)，
-- 结算时购物车里买了什么完全没有落库——用户查不到自己买了什么，
-- 商品下架后也再也说不清那笔订单包含哪些东西。
--
-- product_id 刻意不加外键、可空：
--   管理员删除商品后，历史订单必须仍然完整可读，不能被级联删掉。
--   所以这里存的是「下单当时的快照」(name/price/img)，不是对 products 的引用。

CREATE TABLE IF NOT EXISTS order_items (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    product_id BIGINT,
    name       TEXT NOT NULL,
    price      DOUBLE PRECISION NOT NULL DEFAULT 0,
    quantity   INTEGER NOT NULL DEFAULT 1 CHECK (quantity > 0),
    img        TEXT NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_order_items_order ON order_items(order_id);

-- price 用 DOUBLE PRECISION 而非 NUMERIC，与 products.price / orders.total 保持一致：
--   PostgREST 会把 NUMERIC 序列化成 JSON 字符串，
--   前端 `price * quantity` 会静默变成字符串拼接（"198" * 2 = 396 看着对，
--   但 "198" + 2 = "1982"；金额汇总处一旦用 + 就是灾难）。
--   DOUBLE PRECISION 与旧 SQLite 的 REAL 语义逐字对应。


-- ---------- 3. carts 补数量 ----------
-- 在此之前重复加购是插入多行相同商品，前端按「数组下标」删除，
-- 且合计完全忽略数量。改为一行一商品 + quantity。

ALTER TABLE carts ADD COLUMN IF NOT EXISTS quantity INTEGER NOT NULL DEFAULT 1;

-- 同一用户同一商品只应有一行：加购时若已存在则数量累加。
-- 注意：如果历史数据里已有重复行，这个唯一索引会创建失败。
-- 下面的 DO 块会先探测并提示，绝不静默删数据。
DO $$
DECLARE
    dup_count BIGINT;
BEGIN
    SELECT COUNT(*) INTO dup_count FROM (
        SELECT username, (product->>'id') AS pid
          FROM carts
         GROUP BY username, (product->>'id')
        HAVING COUNT(*) > 1
    ) d;

    IF dup_count > 0 THEN
        RAISE NOTICE 'carts 表存在 % 组重复的 (用户名, 商品) 组合，已跳过唯一索引创建。', dup_count;
        RAISE NOTICE '如需启用「加购累加」，请先自行合并这些行，再重新执行本脚本。';
    ELSE
        CREATE UNIQUE INDEX IF NOT EXISTS idx_carts_user_product
            ON carts(username, ((product->>'id')));
        RAISE NOTICE 'carts 唯一索引已就绪（加购将累加数量而不再插重复行）';
    END IF;
EXCEPTION
    WHEN undefined_column THEN
        RAISE NOTICE 'carts.product 不是 JSONB，跳过唯一索引创建';
END $$;


-- ---------- 4. 下单函数（原子写订单 + 明细）----------
-- 为什么必须放在数据库函数里：
--   PostgREST 客户端无法开事务，若用两次 .insert() 完成「写订单 + 写明细」，
--   第二步失败时会留下一笔没有明细的订单——用户付了钱却查不到买了什么，
--   而且这种半成品数据没有任何报错提示。函数体内是单个事务，要么全成要么全无。
--
-- p_items 形如：[{"product_id":1,"name":"冀筑华塔微藏盒","price":198,"quantity":2,"img":"/images/001.jpg"}]

CREATE OR REPLACE FUNCTION create_order(
    p_username TEXT,
    p_total    DOUBLE PRECISION,
    p_address  TEXT DEFAULT '',
    p_phone    TEXT DEFAULT '',
    p_items    JSONB DEFAULT '[]'::jsonb
)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_order_id BIGINT;
    v_order_no TEXT;
BEGIN
    -- 订单号：JY + 日期 + 6 位随机，给用户看的，不暴露自增 id
    v_order_no := 'JY' || to_char(NOW(), 'YYYYMMDD') || '-'
                  || upper(substr(md5(random()::text || clock_timestamp()::text), 1, 6));

    INSERT INTO orders (username, total, address, phone, order_no, status)
    VALUES (p_username, COALESCE(p_total, 0), COALESCE(p_address, ''),
            COALESCE(p_phone, ''), v_order_no, '待发货')
    RETURNING id INTO v_order_id;

    -- 明细：只接受 JSONB 数组；传空数组时订单就是一笔无明细的订单（历史行为兼容）
    IF p_items IS NOT NULL AND jsonb_typeof(p_items) = 'array' AND jsonb_array_length(p_items) > 0 THEN
        INSERT INTO order_items (order_id, product_id, name, price, quantity, img)
        SELECT
            v_order_id,
            NULLIF(item->>'product_id', '')::BIGINT,
            COALESCE(item->>'name', '未知商品'),
            COALESCE(NULLIF(item->>'price', '')::DOUBLE PRECISION, 0),
            GREATEST(COALESCE(NULLIF(item->>'quantity', '')::INTEGER, 1), 1),
            COALESCE(item->>'img', '')
        FROM jsonb_array_elements(p_items) AS item;
    END IF;

    RETURN v_order_id;
END $$;


-- ---------- 5. 搜索 / 分类浏览 ----------
-- 为什么搜索也做成函数，而不是 supabase-js 的 .ilike('name', '%词%')：
--   supabase-js 不会对 pattern 做百分号转义，带中文的 pattern 曾导致
--   Supabase 边缘节点直接拒绝请求（Cloudflare error 1101 / HTTP 556）。
--   这里关键词是用户输入的，风险更高。
--   走 RPC 后参数放在请求体的 JSON 里，由 supabase-js 自行序列化，天然安全。
--
-- sort 取值：default / price_asc / price_desc / newest
-- 排序末尾总是补 id，保证分页稳定（否则价格相同的商品在翻页时会重复或漏掉）。

CREATE OR REPLACE FUNCTION search_products(
    p_q                TEXT    DEFAULT '',
    p_category         TEXT    DEFAULT '',
    p_sort             TEXT    DEFAULT 'default',
    p_page             INTEGER DEFAULT 1,
    p_size             INTEGER DEFAULT 12,
    p_include_inactive BOOLEAN DEFAULT FALSE
)
RETURNS TABLE(items JSONB, total BIGINT)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
    WITH filtered AS (
        SELECT * FROM products
         WHERE (COALESCE(p_include_inactive, FALSE) OR active = 1)
           AND (COALESCE(p_category, '') = '' OR category = p_category)
           AND (COALESCE(p_q, '') = '' OR name ILIKE '%' || p_q || '%')
    ),
    -- 排序只在这里算一次，产出序号 rn。
    -- 踩过的坑：曾经写成 page_rows 排好序、最后 jsonb_agg(to_jsonb(p) ORDER BY p.id)，
    -- 那个 ORDER BY p.id 会把排好的结果**按 id 重排回去**，价格升降序全部失效
    -- （表现：sort=price_asc 和 sort=price_desc 返回同一个顺序）。
    -- 现在分页和聚合都跟着 rn 走，两处不可能再不一致。
    page_rows AS (
        SELECT p.*,
               ROW_NUMBER() OVER (
                   ORDER BY
                       CASE WHEN p_sort = 'price_asc'  THEN p.price      END ASC,
                       CASE WHEN p_sort = 'price_desc' THEN p.price      END DESC,
                       CASE WHEN p_sort = 'newest'     THEN p.created_at END DESC,
                       p.id ASC
               ) AS rn
          FROM filtered p
    ),
    paged AS (
        SELECT * FROM page_rows
         ORDER BY rn
         OFFSET GREATEST((COALESCE(p_page, 1) - 1) * COALESCE(p_size, 12), 0)
         LIMIT  COALESCE(p_size, 12)
    )
    SELECT
        -- 减掉 'rn'：它是排序用的内部列，不该出现在接口返回值里
        COALESCE((SELECT jsonb_agg(to_jsonb(p) - 'rn' ORDER BY p.rn) FROM paged p), '[]'::jsonb),
        (SELECT COUNT(*) FROM filtered);
$$;


-- 分类清单（给「分类浏览」页用）：返回分类名 + 该分类下已上架商品数
CREATE OR REPLACE FUNCTION get_categories()
RETURNS TABLE(category TEXT, cnt BIGINT)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT category, COUNT(*) AS cnt
      FROM products
     WHERE active = 1
     GROUP BY category
     ORDER BY cnt DESC, category ASC;
$$;


-- ---------- 6. 权限 ----------
-- 后端只用 service_role 密钥（仅存在于 Render 服务端，绝不下发到浏览器）。
-- 新增的表和函数必须单独授权，否则 service_role 也读不到
-- （supabase-init.sql 里的默认授权不覆盖后建的对象）。

GRANT SELECT, INSERT, UPDATE, DELETE ON order_items TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;

-- 只给 service_role，刻意不给 anon / authenticated：
-- create_order 能凭空造订单，暴露给浏览器等于让人随便刷营收。
GRANT EXECUTE ON FUNCTION create_order(TEXT, DOUBLE PRECISION, TEXT, TEXT, JSONB) TO service_role;
GRANT EXECUTE ON FUNCTION search_products(TEXT, TEXT, TEXT, INTEGER, INTEGER, BOOLEAN) TO service_role;
GRANT EXECUTE ON FUNCTION get_categories() TO service_role;


-- ---------- 7. 自检 ----------
-- 期望：3 行 —— create_order / search_products / get_categories 都就绪
SELECT proname, pg_get_function_arguments(oid) AS args
  FROM pg_proc
 WHERE proname IN ('create_order', 'search_products', 'get_categories')
 ORDER BY proname;

-- 期望：返回 5 个分类及其商品数（文创周边 2 / 数字画作 2 / 数字藏品 2 / 典藏精品 2 / 非遗手作 4）
SELECT * FROM get_categories();

-- 期望：total = 1（只有「赵州桥榫卯奇盒」命中）
SELECT total, jsonb_array_length(items) AS returned
  FROM search_products(p_q => '榫卯', p_size => 10);

-- 期望：价格严格从小到大，最后一条最贵（验证排序没有被重排回去）
SELECT p->>'name' AS name, p->>'price' AS price
  FROM search_products(p_sort => 'price_asc', p_size => 12) s,
       LATERAL jsonb_array_elements(s.items) AS p;

-- 期望：4 行，status/address/phone/order_no 都在
SELECT column_name, data_type, is_nullable, column_default
  FROM information_schema.columns
 WHERE table_schema = 'public' AND table_name = 'orders'
 ORDER BY ordinal_position;

-- 期望：order_items 有 8 列
SELECT column_name, data_type
  FROM information_schema.columns
 WHERE table_schema = 'public' AND table_name = 'order_items'
 ORDER BY ordinal_position;

-- 期望：quantity 出现
SELECT column_name, data_type, column_default
  FROM information_schema.columns
 WHERE table_schema = 'public' AND table_name = 'carts'
 ORDER BY ordinal_position;

-- 期望：existing_orders 是你现有的订单数（本脚本不改变它），
--       items_total 为 0（历史订单没有明细，属预期——它们下单时确实没记录）
SELECT
    (SELECT COUNT(*) FROM orders)                               AS existing_orders,
    (SELECT COUNT(*) FROM order_items)                          AS items_total,
    (SELECT COUNT(*) FROM orders WHERE status = '待发货')        AS pending_orders;
