-- ============================================================
-- 002 分类、商品、规格、SKU、库存
-- ============================================================

CREATE TABLE IF NOT EXISTS categories (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL UNIQUE,
    sort_order  INTEGER NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE products ADD COLUMN IF NOT EXISTS category_id BIGINT REFERENCES categories(id);
ALTER TABLE products ADD COLUMN IF NOT EXISTS subtitle TEXT NOT NULL DEFAULT '';
ALTER TABLE products ADD COLUMN IF NOT EXISTS description TEXT NOT NULL DEFAULT '';
ALTER TABLE products ADD COLUMN IF NOT EXISTS cover_img TEXT NOT NULL DEFAULT '';
ALTER TABLE products ADD COLUMN IF NOT EXISTS status INTEGER NOT NULL DEFAULT 1;
ALTER TABLE products ADD COLUMN IF NOT EXISTS sort_order INTEGER NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS sales_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

INSERT INTO categories (name)
SELECT DISTINCT category
  FROM products
 WHERE category IS NOT NULL
   AND category <> ''
ON CONFLICT (name) DO NOTHING;

UPDATE products
   SET category_id = c.id
  FROM categories c
 WHERE products.category_id IS NULL
   AND products.category = c.name;

UPDATE products
   SET cover_img = COALESCE(NULLIF(cover_img, ''), img, ''),
       status = CASE WHEN active = 1 THEN 1 ELSE 0 END
 WHERE cover_img = ''
    OR status IS NULL;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'products_status_check') THEN
        ALTER TABLE products ADD CONSTRAINT products_status_check CHECK (status IN (0, 1));
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'products_sales_check') THEN
        ALTER TABLE products ADD CONSTRAINT products_sales_check CHECK (sales_count >= 0);
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS product_options (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    name        TEXT NOT NULL,
    sort_order  INTEGER NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (product_id, name)
);

CREATE TABLE IF NOT EXISTS product_option_values (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    option_id   BIGINT NOT NULL REFERENCES product_options(id) ON DELETE CASCADE,
    value       TEXT NOT NULL,
    sort_order  INTEGER NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (option_id, value)
);

CREATE TABLE IF NOT EXISTS product_skus (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id     BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    sku_code       TEXT NOT NULL UNIQUE,
    spec_values    JSONB NOT NULL DEFAULT '{}'::jsonb,
    spec_text      TEXT NOT NULL DEFAULT '默认规格',
    price_cents    BIGINT NOT NULL DEFAULT 0,
    stock          INTEGER NOT NULL DEFAULT 0,
    locked_stock   INTEGER NOT NULL DEFAULT 0,
    active         INTEGER NOT NULL DEFAULT 1,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT product_skus_price_check CHECK (price_cents >= 0),
    CONSTRAINT product_skus_stock_check CHECK (stock >= 0),
    CONSTRAINT product_skus_locked_check CHECK (locked_stock >= 0),
    CONSTRAINT product_skus_active_check CHECK (active IN (0, 1))
);

CREATE TABLE IF NOT EXISTS product_sku_option_values (
    sku_id           BIGINT NOT NULL REFERENCES product_skus(id) ON DELETE CASCADE,
    option_value_id  BIGINT NOT NULL REFERENCES product_option_values(id) ON DELETE CASCADE,
    PRIMARY KEY (sku_id, option_value_id)
);

CREATE TABLE IF NOT EXISTS inventory_logs (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku_id            BIGINT NOT NULL REFERENCES product_skus(id),
    order_id          BIGINT,
    change_quantity   INTEGER NOT NULL,
    before_stock      INTEGER NOT NULL,
    after_stock       INTEGER NOT NULL,
    reason            TEXT NOT NULL,
    operator_id       BIGINT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_products_category_status ON products(category_id, status);
CREATE INDEX IF NOT EXISTS idx_product_skus_product ON product_skus(product_id, active);
CREATE INDEX IF NOT EXISTS idx_inventory_logs_sku ON inventory_logs(sku_id, created_at DESC);

INSERT INTO product_skus (product_id, sku_code, spec_values, spec_text, price_cents, stock, active)
SELECT p.id,
       'P' || p.id || '-DEFAULT',
       '{}'::jsonb,
       '默认规格',
       GREATEST(ROUND(COALESCE(p.price, 0) * 100)::BIGINT, 0),
       100,
       CASE WHEN COALESCE(p.active, 1) = 1 THEN 1 ELSE 0 END
  FROM products p
 WHERE NOT EXISTS (
       SELECT 1 FROM product_skus s WHERE s.product_id = p.id
 );

DROP TRIGGER IF EXISTS trg_categories_updated_at ON categories;
CREATE TRIGGER trg_categories_updated_at
BEFORE UPDATE ON categories
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_products_updated_at ON products;
CREATE TRIGGER trg_products_updated_at
BEFORE UPDATE ON products
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_product_skus_updated_at ON product_skus;
CREATE TRIGGER trg_product_skus_updated_at
BEFORE UPDATE ON product_skus
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_options ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_option_values ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_skus ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_sku_option_values ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_logs ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON categories FROM anon, authenticated;
REVOKE ALL ON product_options FROM anon, authenticated;
REVOKE ALL ON product_option_values FROM anon, authenticated;
REVOKE ALL ON product_skus FROM anon, authenticated;
REVOKE ALL ON product_sku_option_values FROM anon, authenticated;
REVOKE ALL ON inventory_logs FROM anon, authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE ON categories TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON product_options TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON product_option_values TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON product_skus TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON product_sku_option_values TO service_role;
GRANT SELECT, INSERT ON inventory_logs TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;
