-- ============================================================
-- 003 购物车与收藏归一化
-- 旧 carts/favorites 使用 username + JSONB product，本脚本迁移为 user_id + SKU/product_id
-- ============================================================

DO $$
BEGIN
    IF to_regclass('public.carts') IS NOT NULL
       AND to_regclass('public.cart_items') IS NULL THEN
        ALTER TABLE carts RENAME TO cart_items;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS cart_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT REFERENCES users(id) ON DELETE CASCADE,
    sku_id      BIGINT REFERENCES product_skus(id) ON DELETE CASCADE,
    quantity    INTEGER NOT NULL DEFAULT 1,
    selected    BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE cart_items ADD COLUMN IF NOT EXISTS user_id BIGINT REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE cart_items ADD COLUMN IF NOT EXISTS sku_id BIGINT REFERENCES product_skus(id) ON DELETE CASCADE;
ALTER TABLE cart_items ADD COLUMN IF NOT EXISTS selected BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE cart_items ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE cart_items ADD COLUMN IF NOT EXISTS quantity INTEGER NOT NULL DEFAULT 1;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
         WHERE table_schema = 'public' AND table_name = 'cart_items' AND column_name = 'username'
    ) THEN
        EXECUTE $sql$
            UPDATE cart_items c
               SET user_id = u.id
              FROM users u
             WHERE c.user_id IS NULL
               AND c.username = u.username
        $sql$;
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns
         WHERE table_schema = 'public' AND table_name = 'cart_items' AND column_name = 'product'
    ) THEN
        EXECUTE $sql$
            UPDATE cart_items c
               SET sku_id = s.id
              FROM product_skus s
             WHERE c.sku_id IS NULL
               AND s.product_id = NULLIF(c.product->>'id', '')::BIGINT
               AND s.sku_code = 'P' || (NULLIF(c.product->>'id', '')::BIGINT) || '-DEFAULT'
        $sql$;
    END IF;
END $$;

DELETE FROM cart_items
 WHERE user_id IS NULL OR sku_id IS NULL;

WITH duplicates AS (
    SELECT id,
           ROW_NUMBER() OVER (
               PARTITION BY user_id, sku_id
               ORDER BY id
           ) AS rn
      FROM cart_items
)
DELETE FROM cart_items
 WHERE id IN (SELECT id FROM duplicates WHERE rn > 1);

ALTER TABLE cart_items ALTER COLUMN user_id SET NOT NULL;
ALTER TABLE cart_items ALTER COLUMN sku_id SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'cart_items_quantity_check') THEN
        ALTER TABLE cart_items ADD CONSTRAINT cart_items_quantity_check CHECK (quantity BETWEEN 1 AND 99);
    END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS idx_cart_items_user_sku ON cart_items(user_id, sku_id);
CREATE INDEX IF NOT EXISTS idx_cart_items_user ON cart_items(user_id, created_at DESC);

ALTER TABLE cart_items DROP COLUMN IF EXISTS username;
ALTER TABLE cart_items DROP COLUMN IF EXISTS product;

DROP TRIGGER IF EXISTS trg_cart_items_updated_at ON cart_items;
CREATE TRIGGER trg_cart_items_updated_at
BEFORE UPDATE ON cart_items
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

ALTER TABLE favorites ADD COLUMN IF NOT EXISTS user_id BIGINT REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE favorites ADD COLUMN IF NOT EXISTS product_id BIGINT REFERENCES products(id) ON DELETE CASCADE;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
         WHERE table_schema = 'public' AND table_name = 'favorites' AND column_name = 'username'
    ) THEN
        EXECUTE $sql$
            UPDATE favorites f
               SET user_id = u.id
              FROM users u
             WHERE f.user_id IS NULL
               AND f.username = u.username
        $sql$;
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns
         WHERE table_schema = 'public' AND table_name = 'favorites' AND column_name = 'product'
    ) THEN
        EXECUTE $sql$
            UPDATE favorites f
               SET product_id = NULLIF(f.product->>'id', '')::BIGINT
             WHERE f.product_id IS NULL
        $sql$;
    END IF;
END $$;

DELETE FROM favorites
 WHERE user_id IS NULL OR product_id IS NULL;

WITH duplicates AS (
    SELECT id,
           ROW_NUMBER() OVER (
               PARTITION BY user_id, product_id
               ORDER BY id
           ) AS rn
      FROM favorites
)
DELETE FROM favorites
 WHERE id IN (SELECT id FROM duplicates WHERE rn > 1);

ALTER TABLE favorites ALTER COLUMN user_id SET NOT NULL;
ALTER TABLE favorites ALTER COLUMN product_id SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_favorites_user_product ON favorites(user_id, product_id);
CREATE INDEX IF NOT EXISTS idx_favorites_user_created ON favorites(user_id, created_at DESC);

ALTER TABLE favorites DROP COLUMN IF EXISTS username;
ALTER TABLE favorites DROP COLUMN IF EXISTS product;

ALTER TABLE cart_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE favorites ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON cart_items FROM anon, authenticated;
REVOKE ALL ON favorites FROM anon, authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE ON cart_items TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON favorites TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;
