-- ============================================================
-- 004 订单、订单项、状态日志、退款、演示支付
-- ============================================================

ALTER TABLE orders ADD COLUMN IF NOT EXISTS user_id BIGINT REFERENCES users(id);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_status TEXT NOT NULL DEFAULT 'unpaid';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_method TEXT NOT NULL DEFAULT 'wechat';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS goods_amount_cents BIGINT NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS discount_amount_cents BIGINT NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payable_amount_cents BIGINT NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS paid_amount_cents BIGINT NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS receiver_name TEXT NOT NULL DEFAULT '';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS receiver_phone TEXT NOT NULL DEFAULT '';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS receiver_province TEXT NOT NULL DEFAULT '';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS receiver_city TEXT NOT NULL DEFAULT '';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS receiver_district TEXT NOT NULL DEFAULT '';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS receiver_detail TEXT NOT NULL DEFAULT '';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS remark TEXT NOT NULL DEFAULT '';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS cancel_reason TEXT NOT NULL DEFAULT '';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS paid_at TIMESTAMPTZ;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS shipped_at TIMESTAMPTZ;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMPTZ;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

UPDATE orders o
   SET user_id = u.id
  FROM users u
 WHERE o.user_id IS NULL
   AND o.username = u.username;

UPDATE orders
   SET goods_amount_cents = GREATEST(ROUND(COALESCE(total, 0) * 100)::BIGINT, 0),
       payable_amount_cents = GREATEST(ROUND(COALESCE(total, 0) * 100)::BIGINT, 0),
       paid_amount_cents = CASE
           WHEN status IN ('待发货', '已发货', '已完成') THEN GREATEST(ROUND(COALESCE(total, 0) * 100)::BIGINT, 0)
           ELSE 0
       END,
       payment_status = CASE
           WHEN status IN ('待发货', '已发货', '已完成') THEN 'paid'
           ELSE 'unpaid'
       END
 WHERE goods_amount_cents = 0
   AND payable_amount_cents = 0;

UPDATE orders
   SET status = '待发货'
 WHERE status IS NULL
    OR status NOT IN ('待付款', '待发货', '已发货', '已完成', '已取消');

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'orders_status_check_v2') THEN
        ALTER TABLE orders ADD CONSTRAINT orders_status_check_v2
        CHECK (status IN ('待付款', '待发货', '已发货', '已完成', '已取消'));
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'orders_payment_status_check_v2') THEN
        ALTER TABLE orders ADD CONSTRAINT orders_payment_status_check_v2
        CHECK (payment_status IN ('unpaid', 'paid', 'refund_requested', 'refunded', 'refund_rejected'));
    END IF;
END $$;

ALTER TABLE order_items ADD COLUMN IF NOT EXISTS sku_id BIGINT REFERENCES product_skus(id);
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS product_name TEXT NOT NULL DEFAULT '';
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS sku_spec_text TEXT NOT NULL DEFAULT '默认规格';
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS product_img TEXT NOT NULL DEFAULT '';
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS price_cents BIGINT NOT NULL DEFAULT 0;
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS subtotal_cents BIGINT NOT NULL DEFAULT 0;
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

UPDATE order_items
   SET product_name = COALESCE(NULLIF(product_name, ''), name, '未知商品'),
       product_img = COALESCE(NULLIF(product_img, ''), img, ''),
       price_cents = CASE
           WHEN price_cents = 0 THEN GREATEST(ROUND(COALESCE(price, 0) * 100)::BIGINT, 0)
           ELSE price_cents
       END,
       subtotal_cents = CASE
           WHEN subtotal_cents = 0 THEN GREATEST(ROUND(COALESCE(price, 0) * 100)::BIGINT * COALESCE(quantity, 1), 0)
           ELSE subtotal_cents
       END;

CREATE TABLE IF NOT EXISTS order_status_logs (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id       BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    from_status    TEXT,
    to_status      TEXT NOT NULL,
    operator_id    BIGINT,
    operator_role  TEXT NOT NULL DEFAULT 'system',
    remark         TEXT NOT NULL DEFAULT '',
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS refund_requests (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id       BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    user_id        BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    reason         TEXT NOT NULL,
    amount_cents   BIGINT NOT NULL DEFAULT 0,
    status         TEXT NOT NULL DEFAULT '待处理',
    admin_note     TEXT NOT NULL DEFAULT '',
    handled_by     BIGINT REFERENCES users(id),
    applied_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    handled_at     TIMESTAMPTZ,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT refund_requests_status_check CHECK (status IN ('待处理', '已同意', '已拒绝', '已撤销'))
);

CREATE TABLE IF NOT EXISTS payment_records (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id         BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    user_id          BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    method           TEXT NOT NULL,
    amount_cents     BIGINT NOT NULL,
    transaction_no   TEXT NOT NULL UNIQUE,
    status           TEXT NOT NULL DEFAULT 'success',
    paid_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT payment_records_status_check CHECK (status IN ('success', 'refunded', 'failed'))
);

CREATE INDEX IF NOT EXISTS idx_orders_user_created ON orders(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_status_created ON orders(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_order_items_order ON order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_order_status_logs_order ON order_status_logs(order_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_refund_requests_order ON refund_requests(order_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_refund_requests_status ON refund_requests(status, created_at DESC);

DROP TRIGGER IF EXISTS trg_orders_updated_at ON orders;
CREATE TRIGGER trg_orders_updated_at
BEFORE UPDATE ON orders
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_status_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE refund_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment_records ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON orders FROM anon, authenticated;
REVOKE ALL ON order_items FROM anon, authenticated;
REVOKE ALL ON order_status_logs FROM anon, authenticated;
REVOKE ALL ON refund_requests FROM anon, authenticated;
REVOKE ALL ON payment_records FROM anon, authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE ON orders TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON order_items TO service_role;
GRANT SELECT, INSERT ON order_status_logs TO service_role;
GRANT SELECT, INSERT, UPDATE ON refund_requests TO service_role;
GRANT SELECT, INSERT, UPDATE ON payment_records TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;
